### ISSUE TITLE
BUG: New budget is not working on the Docker version.

### ISSUE THREAD

**Issue by mariushosting** [rare-magma/guitos#149]
Nothing happen when you try to add new budget.

**Comment by rare-magma** [comment]
@mariushosting can you please provide more information about your problem? Details such as:  

1. what you're trying to do
2. step by step recollection of what you have done
3. copy of error message if any
4. details about your docker/server setup
5. anything else you might find relevant

**Comment by mariushosting** [comment]
> @mariushosting can you please provide more information about your problem? Details such as:
> 
> 1. what you're trying to do
> 2. step by step recollection of what you have done
> 3. copy of error message if any
> 4. details about your docker/server setup
> 5. anything else you might find relevant

![nothing](https://github.com/user-attachments/assets/88c957cd-1b20-4650-b79f-8abef47a36cc)


Nothing happen when I click those buttons. 
Docker version 24.02
There is no error logs in the container.

**Comment by rare-magma** [comment]
thanks for the additional info @mariushosting. 
When you click on the new or get started buttons guitos requests additional assets from the docker container, perhaps there's something wrong with the network configuration?
You can confirm what is the problem by checking if there's any errors in the browser's developer tools network panel.
Here's how to open the network panel: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Tools_and_setup/What_are_browser_developer_tools#how_to_open_the_devtools_in_your_browser

When you click the new button you should see these types of successful requests:
![image](https://github.com/user-attachments/assets/9dc953a1-88f7-4b26-a51f-f7a91afcd551)

**Comment by mariushosting** [comment]
![issues](https://github.com/user-attachments/assets/1ec65dd1-b1e7-4a84-82bf-c04426498e8b)

**Comment by rare-magma** [comment]
@mariushosting can you try it again with the latest docker image that was published a few min ago? It includes a fix that might solve your problem.
If the issue is still present after trying the new version please post a screenshot with the network panel open and the requests visible as in this screenshot:
![image](https://github.com/user-attachments/assets/281dd4b0-6869-4543-a76e-374d9e2fb00d)

**Comment by mariushosting** [comment]
> @mariushosting can you try it again with the latest docker image that was published a few min ago? It includes a fix that might solve your problem. If the issue is still present after trying the new version please post a screenshot with the network panel open and the requests visible as in this screenshot: ![image](https://private-user-images.githubusercontent.com/45106055/378090910-281dd4b0-6869-4543-a76e-374d9e2fb00d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNDY3MTMsIm5iZiI6MTcyOTM0NjQxMywicGF0aCI6Ii80NTEwNjA1NS8zNzgwOTA5MTAtMjgxZGQ0YjAtNjg2OS00NTQzLWE3NmUtMzc0ZDllMmZiMDBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDE0MDAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwYWE3NWUyYzcyZTMwZTI3YTc5YjVhYTgwYmU1MGE0MDk4N2ZlNGM1ZWY3YjhjMmQwZDYxZTVhODYzODZiMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OjNSEHDiKkXdqAupMHWM1gaMAEKz8XV678wMEH0lVMs)


![not work2](https://github.com/user-attachments/assets/d6592bc6-8b18-49fa-b517-bdf72bdc40ef)

Latest image still not work

**Comment by rare-magma** [comment]
thanks for the screenshot, it looks like this problem is caused by the fact that browsers block the usage of a cryptographic function that guitos uses to create unique identifiers for budgets, as referenced in [here](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID). 
In order to solve this problem you'll have to change your setup to serve this app with https or override the browser's security mechanism and add an exception for the container's IP as described in [here](https://stackoverflow.com/questions/40696280/unsafely-treat-insecure-origin-as-secure-flag-is-not-working-on-chrome#53388534)

**Comment by mariushosting** [comment]
> thanks for the screenshot, it looks like this problem is caused by the fact that browsers block the usage of a cryptographic function that guitos uses to create unique identifiers for budgets, as referenced in [here](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID). In order to solve this problem you'll have to change your setup to serve this app with https or override the browser's security mechanism and add an exception for the container's IP as described in [here](https://stackoverflow.com/questions/40696280/unsafely-treat-insecure-origin-as-secure-flag-is-not-working-on-chrome#53388534)

You are right this works only on https://
You can check here: https://guitos.mariushosting.synology.me/
But for people that want it to run on localhost?

**Comment by rare-magma** [comment]
localhost is considered secure: https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts#when_is_a_context_considered_secure
